// src/ui/filemanager/src/main_window/deps.h
// Role: Compile-time dependency bundle for MainWindow implementation units.

#pragma once

#include <QAbstractButton>
#include <QAbstractItemView>
#include <QAction>
#include <QActionGroup>
#include <QApplication>
#include <QButtonGroup>
#include <QCloseEvent>
#include <QComboBox>
#include <QCoreApplication>
#include <QDesktopServices>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDragEnterEvent>
#include <QDragMoveEvent>
#include <QDropEvent>
#include <QFile>
#include <QFileDialog>
#include <QFileSystemModel>
#include <QFileSystemWatcher>
#include <QFormLayout>
#include <QGuiApplication>
#include <QGroupBox>
#include <QHeaderView>
#include <QHBoxLayout>
#include <QInputDialog>
#include <QItemSelectionModel>
#include <QKeyEvent>
#include <QLabel>
#include <QLineEdit>
#include <QListView>
#include <QListWidget>
#include <QMenu>
#include <QMenuBar>
#include <QMessageBox>
#include <QMetaObject>
#include <QMimeData>
#include <QPainter>
#include <QPlainTextEdit>
#include <QProcess>
#include <QPushButton>
#include <QRadioButton>
#include <QRegularExpression>
#include <QScrollBar>
#include <QScreen>
#include <QSignalBlocker>
#include <QSet>
#include <QSplitter>
#include <QStackedWidget>
#include <QStatusBar>
#include <QStorageInfo>
#include <QStyleOptionViewItem>
#include <QTableWidget>
#include <QTemporaryDir>
#include <QTimer>
#include <QToolBar>
#include <QToolButton>
#include <QTreeView>
#include <QUrl>
#include <QVBoxLayout>

#include <optional>

#include "archive_session.h"
#include "archive_error.h"
#include "descript_ion_store.h"
#include "app_startup_qt.h"
#include "drag_drop_policy_qt.h"
#include "portable_settings.h"
#include "archive_process_runner.h"
#include "checksum_result_dialog.h"
#include "official_lang_catalog.h"
#include "options_dialog.h"
#include "filemanager_task_progress_dialog.h"
#include "task_ipc_runtime.h"
#include "shared/column_width_persistence.h"
#include "drag_drop/drag_aware_views.h"
#include "structured_list_proxy.h"
